import re

def clean_markdown(content: str) -> str:
    """
    Cleans and optimizes Markdown content generated by AI.
    """
    if not content:
        return ""

    # 1. Remove Markdown code block wrappers
    # Matches ```markdown\n ... \n``` or ```\n ... \n```
    code_block_pattern = r"^```(?:markdown)?\s*\n(.*?)\n```$"
    match = re.search(code_block_pattern, content, re.DOTALL | re.IGNORECASE)
    if match:
        content = match.group(1)

    # 2. Remove leading conversational filler (simple heuristic)
    # If the text starts with something like "Here is the analysis..." and then has a header
    # We look for the first header `###` or `##` or `#`
    header_match = re.search(r"^(#+)\s", content, re.MULTILINE)
    if header_match:
        start_index = header_match.start()
        # If there's text before the first header, check if it looks like filler
        pre_header_text = content[:start_index].strip()
        if pre_header_text and len(pre_header_text) < 100: # Arbitrary length check
             # If it's short, it's likely "Here is your analysis:"
             content = content[start_index:]
    
    # 3. Ensure proper spacing for headers
    # Ensure space after #
    content = re.sub(r"^(#+)([^ \n])", r"\1 \2", content, flags=re.MULTILINE)
    
    # 4. Ensure proper spacing for list items
    # Ensure space after - or * or 1.
    content = re.sub(r"^(\s*[-*])([^ \n])", r"\1 \2", content, flags=re.MULTILINE)
    
    # 5. Fix multiple consecutive blank lines (max 2)
    content = re.sub(r"\n{3,}", "\n\n", content)

    # 6. Ensure bold syntax is correct (basic check)
    # ** text** -> **text**
    content = re.sub(r"\*\*\s+(.*?)\s+\*\*", r"**\1**", content)

    return content.strip()
